dist: trusty
language: java
#addons:
#  chrome: stable
addons:
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable
  chrome: stable

env:
  global:
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
#  - whereis google-chrome-stable
#  - whereis chromedriver
#   - "ls -lhisa /usr/bin/"
   - "find / -name chromedriver*"
#  - "mvn test"
